apiVersion: apps/v1beta1
kind: Deployment # it is a deployment
metadata:
  name: angular-universal-deployment # name of the Deployment
  labels:
    # any Pods with matching labels are included in this Deployment
    app: angular-universal
    tier: angular-universal-tier
spec:
  # ReplicaSet specification
  replicas: 3 # we are making 3 Pods
  selector:
    matchLabels:
      # ReplicaSet labels will match Pods with the following labels
      tier: angular-universal-tier
  template:
    # Pod template
    metadata:
      labels:
        # Pod's labels
        app: angular-universal
        tier: angular-universal-tier
    spec:
      # Pod specification
      containers:
        # the container(s) in this Pod
        - name: angular-universal-container
          image: CONTAINER
          # the readiness probe details
          readinessProbe:
            httpGet: # make an HTTP request
              port: 8080 # port to use
              path: /readiness # endpoint to hit
              scheme: HTTP # or HTTPS
            initialDelaySeconds: 3 # how long to wait before checking
            periodSeconds: 3 # how long to wait between checks
            successThreshold: 1 # how many successes to hit before accepting
            failureThreshold: 1 # how many failures to accept before failing
            timeoutSeconds: 1 # how long to wait for a response
          # the livenessProbe probe details
          livenessProbe:
            httpGet: # make an HTTP request
              port: 8080 # port to use
              path: /healthcheck # endpoint to hit
              scheme: HTTP # or HTTPS
            initialDelaySeconds: 3 # how long to wait before checking
            periodSeconds: 3 # how long to wait between checks
            successThreshold: 1 # how many successes to hit before accepting
            failureThreshold: 1 # how many failures to accept before failing
            timeoutSeconds: 1 # how long to wait for a response
          # environment variables for the Pod
          env:
            - name: NODE_ENV
              value: production
          ports:
            - containerPort: 4000